RSP={r=1,s=2,p=3}
RSP_result = {{RSP.r, RSP.s, RSP.p}, --normal
							{RSP.s, RSP.p, RSP.r}, --win
							{RSP.p, RSP.r, RSP.s}} --lose
festival = false

function init(self)
	math.randomseed(os.time()*os.clock())
  msg.post(".", "acquire_input_focus")
  win_count = 0
	max_count = 0
	lose_count = 0
	rnd = 0
  r_node = gui.get_node("r_button")
  s_node = gui.get_node("s_button")
  p_node = gui.get_node("p_button")
  buttons_node = gui.get_node("buttons")
  start_node = gui.get_node("start_button")
  name_node = gui.get_node("name")
  win_node = gui.get_node("win_number")
	max_node = gui.get_node("max_number")
  player1_node = gui.get_node("player_r")
  player2_node = gui.get_node("player_s")
  player3_node = gui.get_node("player_p")
  enemy1_node = gui.get_node("enemy_r")
  enemy2_node = gui.get_node("enemy_s")
  enemy3_node = gui.get_node("enemy_p")
  gui.set_color(buttons_node, vmath.vector4(gui.get_color(buttons_node).x, gui.get_color(buttons_node).y, gui.get_color(buttons_node).z, 0))
  gui.set_color(name_node, vmath.vector4(gui.get_color(name_node).x, gui.get_color(name_node).y, gui.get_color(name_node).z, 0))
  gui.set_color(player1_node, vmath.vector4(gui.get_color(player1_node).x, gui.get_color(player1_node).y, gui.get_color(player1_node).z, 0))
  gui.set_color(player2_node, vmath.vector4(gui.get_color(player2_node).x, gui.get_color(player2_node).y, gui.get_color(player2_node).z, 0))
  gui.set_color(player3_node, vmath.vector4(gui.get_color(player3_node).x, gui.get_color(player3_node).y, gui.get_color(player3_node).z, 0))
  gui.set_color(enemy1_node, vmath.vector4(gui.get_color(enemy1_node).x, gui.get_color(enemy1_node).y, gui.get_color(enemy1_node).z, 0))
  gui.set_color(enemy2_node, vmath.vector4(gui.get_color(enemy2_node).x, gui.get_color(enemy2_node).y, gui.get_color(enemy2_node).z, 0))
  gui.set_color(enemy3_node, vmath.vector4(gui.get_color(enemy3_node).x, gui.get_color(enemy3_node).y, gui.get_color(enemy3_node).z, 0))
--windowの設定
	if system_name == "Windows" then
		defos.disable_window_resize()
		defos.disable_minimize_button()
		defos.disable_maximize_button()
		defos.set_always_on_top(festival)
		display = defos.get_displays()
		display_id = defos.get_current_display_id()
		defos.set_view_size((display[display_id].bounds.width - 1280) / 2, (display[display_id].bounds.height - 720) / 2, 1280, 720)
		defos.set_console_visible(false)
	end
end

function update(self, dt)
  gui.set_text(win_node, win_count.."連勝中")
	gui.set_text(max_node, "最高記録  "..max_count.."勝")
	if win_count == 0 then
		lose_count = 0
	else
		lose_count = (win_count-win_count%10+30)
	end

	if max_count <= win_count then
		max_count = win_count
	end
end

function on_input(self, action_id, action)
  if action_id == hash("click") and action.pressed then
		if gui.pick_node(gui.get_node("close_button"), action.x, action.y) then
			sys.exit(0)
    elseif gui.pick_node(gui.get_node("r_button"), action.x, action.y) and gui.get_color(name_node).w == 1 then
      battle(RSP.r)
      gui.set_color(player1_node, vmath.vector4(gui.get_color(player1_node).x, gui.get_color(player1_node).y, gui.get_color(player1_node).z, 1))
      gui.set_color(player2_node, vmath.vector4(gui.get_color(player2_node).x, gui.get_color(player2_node).y, gui.get_color(player2_node).z, 0))
      gui.set_color(player3_node, vmath.vector4(gui.get_color(player3_node).x, gui.get_color(player3_node).y, gui.get_color(player3_node).z, 0))
    elseif gui.pick_node(gui.get_node("s_button"), action.x, action.y) and gui.get_color(name_node).w == 1 then
      battle(RSP.s)
      gui.set_color(player1_node, vmath.vector4(gui.get_color(player1_node).x, gui.get_color(player1_node).y, gui.get_color(player1_node).z, 0))
      gui.set_color(player2_node, vmath.vector4(gui.get_color(player2_node).x, gui.get_color(player2_node).y, gui.get_color(player2_node).z, 1))
      gui.set_color(player3_node, vmath.vector4(gui.get_color(player3_node).x, gui.get_color(player3_node).y, gui.get_color(player3_node).z, 0))
    elseif gui.pick_node(gui.get_node("p_button"), action.x, action.y) and gui.get_color(name_node).w == 1 then
      battle(RSP.p)
      gui.set_color(player1_node, vmath.vector4(gui.get_color(player1_node).x, gui.get_color(player1_node).y, gui.get_color(player1_node).z, 0))
      gui.set_color(player2_node, vmath.vector4(gui.get_color(player2_node).x, gui.get_color(player2_node).y, gui.get_color(player2_node).z, 0))
      gui.set_color(player3_node, vmath.vector4(gui.get_color(player3_node).x, gui.get_color(player3_node).y, gui.get_color(player3_node).z, 1))
    elseif gui.pick_node(gui.get_node("start_button"), action.x, action.y) and gui.get_color(start_node).w == 1 or not game_flag then
      gui.set_color(gui.get_node("start_button"), vmath.vector4(gui.get_color(start_node).x, gui.get_color(start_node).y, gui.get_color(start_node).z, 0))
      gui.set_color(buttons_node, vmath.vector4(gui.get_color(buttons_node).x, gui.get_color(buttons_node).y, gui.get_color(buttons_node).z, 1))
      gui.set_color(name_node, vmath.vector4(gui.get_color(name_node).x, gui.get_color(name_node).y, gui.get_color(name_node).z, 1))
			gui.set_color(gui.get_node("result_text_node"), vmath.vector4(0, 0, 0, 0))--PC
			gui.set_text(gui.get_node("result_text_node"), "出す手を選んでね♡")
    end
	elseif action_id == hash("esc") then
		sys.exit(0)
  end
end

function battle(input)
	rnd = math.random()*100
	opponent_result = 0
	if rnd > lose_count then
		opponent_result = RSP_result[2][input]--勝ち
		win_count = win_count + 1
		gui.set_color(gui.get_node("result_text_node"), vmath.vector4(1, 0, 0, 1))
		gui.set_text(gui.get_node("result_text_node"), "勝ち")
	elseif rnd < lose_count/3 then
		opponent_result = RSP_result[3][input]--負け
		win_count = 0
		gui.set_color(gui.get_node("result_text_node"), vmath.vector4(0, 0, 1, 1))
		gui.set_text(gui.get_node("result_text_node"), "負け")
	else
		gui.set_color(gui.get_node("result_text_node"), vmath.vector4(0, 0, 0, 1))
		gui.set_text(gui.get_node("result_text_node"), "あいこ")
		opponent_result = RSP_result[1][input]--あいこ
	end
	gui.set_color(enemy1_node, vmath.vector4(gui.get_color(enemy1_node).x, gui.get_color(enemy1_node).y, gui.get_color(enemy1_node).z, 0))
  gui.set_color(enemy2_node, vmath.vector4(gui.get_color(enemy2_node).x, gui.get_color(enemy2_node).y, gui.get_color(enemy2_node).z, 0))
  gui.set_color(enemy3_node, vmath.vector4(gui.get_color(enemy3_node).x, gui.get_color(enemy3_node).y, gui.get_color(enemy3_node).z, 0))

	if opponent_result == RSP.r then
		gui.set_color(enemy1_node, vmath.vector4(gui.get_color(enemy1_node).x, gui.get_color(enemy1_node).y, gui.get_color(enemy1_node).z, 1))
	elseif opponent_result == RSP.s then
	  gui.set_color(enemy2_node, vmath.vector4(gui.get_color(enemy2_node).x, gui.get_color(enemy2_node).y, gui.get_color(enemy2_node).z, 1))
	elseif opponent_result == RSP.p then
	  gui.set_color(enemy3_node, vmath.vector4(gui.get_color(enemy3_node).x, gui.get_color(enemy3_node).y, gui.get_color(enemy3_node).z, 1))
	end
end
